<a href="https://colab.research.google.com/github/Muhammed1978/Amazon-Product-Review-Analysis/blob/main/DataAnalysis_Pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practical Introduction to Data Analysis with Pandas
  * Pandas is a powerdful Python Library for data analysis that is widely used in fields such as data science , machine learning and statistics.

 * It offers tools for handling and analyzing data in a way that is both efficient and flexible.This guide introduces you to the basics of Pandas, helping you get started with data manipulation and analysis.


# Objectives of this Module

By the end of this tutorial, you will:

 * Understand  the basic functionality of Pandas for data analysis.

 * Learn how to import data from various format (csv, excel etc).

 * Be able to clean and preprocess data effectively.
  
 * Perform basic statistical analysis and visualization.

 **Notice**
  
  * Think of Pandas as an advance version of spread sheet software like Microsoft excel, but with far more powwrful capabilities.

  * It aids you in manipulating and analyizing large data sets with ease.









# Importing th Pandas library

Before you can start using Pandas, you need to import it to Python environment as shown below:




In [ ]:
import pandas as pd


By convention Pandas is imported by alias pd, to make the code shorter and readable.

# Core Components of Pandas Library

The two primary components of pandas on the Series and DataFrame.



# Importing Data with Pandas

* As you can see from various examples ,it is so tedious to start creating DataFrame from scratch.In the data science world , data will be available for you on a spreadsheet such as Ms-Excel.

* Our job as data  sceintiest is to import those datasets using *Pandas*. Pandas can import different format of data such as *.xlsx(Excel data)*, *.csv(comma separated value)*, *.sav(SPSS data)*, *.dat(STATA data)*, or any other *online (the web)*.  

# How to read in data

It's quite simple to load data from various file format into a *DataFrame*. In this section,you will learn how to import different file format with *Pandas*.

In [ ]:
read_data = {"File Format":[".csv", ".xlsx or .xls old Excel file format", ".json",".html", "sas", ".dta", ".sav"],
             "Pandas Function":[".read_csv()", ".read_excel()", ".read_json()", ".read_html()", "read_sas", "read_stata", "read_sav"],
             "Description":["Load delimited data from a file, URl, or file-like object; use comma as default delimiter","Read tabular data from an excel XLS or XLS file", "Read data from a JSON (Javascript Object Notation) string representation", "Read all table found in the given HTML document", "Read a Statistical Analysis Software (SAS) dataset stored in one of the SAS system's custom storage formats", "Read a dataset from Stata file format", "Read a dataset from Statistical Package for Social Sciences(SPSS) file format"]
             }
read_data

{'File Format': ['.csv',
  '.xlsx or .xls old Excel file format',
  '.json',
  '.html',
  'sas',
  '.dta',
  '.sav'],
 'Pandas Function': ['.read_csv()',
  '.read_excel()',
  '.read_json()',
  '.read_html()',
  'read_sas',
  'read_stata',
  'read_sav'],
 'Description': ['Load delimited data from a file, URl, or file-like object; use comma as default delimiter',
  'Read tabular data from an excel XLS or XLS file',
  'Read data from a JSON (Javascript Object Notation) string representation',
  'Read all table found in the given HTML document',
  "Read a Statistical Analysis Software (SAS) dataset stored in one of the SAS system's custom storage formats",
  'Read a dataset from Stata file format',
  'Read a dataset from Statistical Package for Social Sciences(SPSS) file format']}

In [ ]:
import pandas as pd
read_data_df = pd.DataFrame(read_data)
read_data_df

File Format Pandas Function  \
0                                 .csv     .read_csv()   
1  .xlsx or .xls old Excel file format   .read_excel()   
2                                .json    .read_json()   
3                                .html    .read_html()   
4                                  sas        read_sas   
5                                 .dta      read_stata   
6                                 .sav        read_sav   

                                         Description  
0  Load delimited data from a file, URl, or file-...  
1    Read tabular data from an excel XLS or XLS file  
2  Read data from a JSON (Javascript Object Notat...  
3    Read all table found in the given HTML document  
4  Read a Statistical Analysis Software (SAS) dat...  
5              Read a dataset from Stata file format  
6  Read a dataset from Statistical Package for So...

# Import data from CSV

With *.csv* (comma separated value) format all you need is pd.read_csv() comman to load in the data as DataFrame.



# Example 1

Lead the Ethiopian's flowers dataset(Ethiopian_flowers.csv) that was adapted from the well known Iris dataset.Remember the first thing is to import all the necessary libraries such as numpy, pandas etc.

**Note**
 The data is in the datasets folder or directory.

In [ ]:
pwd

'/content'

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
california_housing_test = pd.read_csv("sample_data/california_housing_test.csv")
california_housing_test

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

In [ ]:
california_housing_train = pd.read_csv("sample_data/california_housing_train.csv")
california_housing_train

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

# Exercise

You are to predict the churn from the data

* Churn rate is a measure of the number of customers or employees who leave a company during a given a period.

* It can also refer to the amount of revenue lost as a result of the departures.Changes in a business's churn rate can provide valuable insight into an organization.

**Note**
* Don't forget you need to first do the anlysis to understand the data before modeling.

Submit using the link below:
https://drive.google.com/drive/folders/1g_Y1CGPBK3_nwfMCQbVKOyUw3AOYI9WO


In [ ]:
# Solution of churn rate:
import numpy as np
import pandas as pd
churn_Modelling_Dataset = pd.read_csv("/content/Churn_Modelling Dataset.csv")
churn_Modelling_Dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Churn  
0           101348.88      1  
1           112542.58      0  
2           113931.57      1  
3            93826.63      0  
4            79084.10      0  
...               ...    ...  
9995         96270.64      0  
9996        101699.77      0  
9997         42085.58      1  
9998         92888.52      1  
9999         38190.78      0  

[10000 rows x 14 columns]

In [ ]:
churn_Modelling_Dataset.info


<bound method DataFrame.info of       RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Churn  
0           101348.88      1  
1           112542.58      0  
2           113931.57      1  
3            93826.63      0  
4            79084.10      0  
...               ...    ...  
9995         96270.64      0  
9996        101699.77      0  
9997         42085.58      1  
9998         92888.52      1  
9999         38190.78      0  

[10000 rows x 14 columns]>

In [ ]:
# Calculation of churn rate 1
Churn_rate = churn_Modelling_Dataset['Churn'].value_counts()
Churn_rate

Churn
0    7963
1    2037
Name: count, dtype: int64

In [ ]:
churn_rate = pd.DataFrame(churn_Modelling_Dataset)
churn_rate

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['RowNumber']
  ys = series['CreditScore']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = churn_rate.sort_values('RowNumber', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Geography')):
  _plot_series(series, series_name, i)
  fig.legend(title='Geography', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('RowNumber')
_ = plt.ylabel('CreditScore')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['RowNumber']
  ys = series['CreditScore']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = churn_rate.sort_values('RowNumber', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Gender')):
  _plot_series(series, series_name, i)
  fig.legend(title='Gender', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('RowNumber')
_ = plt.ylabel('CreditScore')

from matplotlib import pyplot as plt
churn_rate['RowNumber'].plot(kind='line', figsize=(8, 4), title='RowNumber')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
churn_rate['CustomerId'].plot(kind='line', figsize=(8, 4), title='CustomerId')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
churn_rate['CreditScore'].plot(kind='line', figsize=(8, 4), title='CreditScore')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
churn_rate['Age'].plot(kind='line', figsize=(8, 4), title='Age')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Gender'].value_counts()
    for x_label, grp in churn_rate.groupby('Geography')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Geography')
_ = plt.ylabel('Gender')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(churn_rate['Geography'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(churn_rate, x='RowNumber', y='Geography', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(churn_rate['Gender'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(churn_rate, x='RowNumber', y='Gender', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(churn_rate['Geography'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(churn_rate, x='CustomerId', y='Geography', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(churn_rate['Gender'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(churn_rate, x='CustomerId', y='Gender', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Churn  
0           101348.88      1  
1           112542.58      0  
2           113931.57      1  
3            93826.63      0  
4            79084.10      0  
...               ...    ...  
9995         96270.64      0  
9996        101699.77      0  
9997         42085.58      1  
9998         92888.52      1  
9999         38190.78      0  

[10000 rows x 14 columns]

In [ ]:
churn_rate.tail()

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Churn  
9995         96270.64      0  
9996        101699.77      0  
9997         42085.58      1  
9998         92888.52      1  
9999         38190.78      0

In [ ]:
churn_rate.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Churn  
0        101348.88      1  
1        112542.58      0  
2        113931.57      1  
3         93826.63      0  
4         79084.10      0

In [ ]:
# Calculation of churn rate 2
# Churn_rate = Amount of revenue lost/dapartures
Churn_rate

Churn
0    7963
1    2037
Name: count, dtype: int64

In [ ]:
!ls -l /content/

total 8
drwx------ 5 root root 4096 Jan  4 13:44 drive
drwxr-xr-x 1 root root 4096 Dec 11 14:34 sample_data


In [ ]:
Promotion_Dataset = pd.read_csv("sample_data/Promotion_Dataset.csv")
Promotion_Dataset

EmployeeNo                                     Division  \
0      YAK/S/00001               Commercial Sales and Marketing   
1      YAK/S/00002        Customer Support and Field Operations   
2      YAK/S/00003               Commercial Sales and Marketing   
3      YAK/S/00004               Commercial Sales and Marketing   
4      YAK/S/00006                     Information and Strategy   
...            ...                                          ...   
38307  YAK/S/54802  Information Technology and Solution Support   
38308  YAK/S/54805        Customer Support and Field Operations   
38309  YAK/S/54806                     Information and Strategy   
38310  YAK/S/54807               Commercial Sales and Marketing   
38311  YAK/S/54808                         People/HR Management   

             Qualification  Gender   Channel_of_Recruitment  \
0         MSc  MBA and PhD  Female  Direct Internal process   
1      First Degree or HND    Male        Agency and others   
2      First Degree or HND    Male  Direct Internal process   
3      First Degree or HND    Male        Agency and others   
4      First Degree or HND    Male  Direct Internal process   
...                    ...     ...                      ...   
38307  First Degree or HND  Female  Direct Internal process   
38308     MSc  MBA and PhD  Female        Agency and others   
38309  First Degree or HND    Male        Agency and others   
38310                  NaN    Male  Direct Internal process   
38311  First Degree or HND    Male        Agency and others   

       Trainings_Attended  Year_of_birth  Last_performance_score  \
0                       2           1986                    12.5   
1                       2           1991                    12.5   
2                       2           1987                     7.5   
3                       3           1982                     2.5   
4                       3           1990                     7.5   
...                   ...            ...                     ...   
38307                   2           1990                     0.0   
38308                   2           1984                     5.0   
38309                   2           1994                    12.5   
38310                   2           1992                     2.5   
38311                   2           1994                     2.5   

       Year_of_recruitment  Targets_met  Previous_Award  \
0                     2011            1               0   
1                     2015            0               0   
2                     2012            0               0   
3                     2009            0               0   
4                     2012            0               0   
...                    ...          ...             ...   
38307                 2018            0               0   
38308                 2013            0               0   
38309                 2016            1               0   
38310                 2017            0               0   
38311                 2014            0               0   

       Training_score_average State_Of_Origin Foreign_schooled Marital_Status  \
0                          41         ANAMBRA               No        Married   
1                          52         ANAMBRA              Yes        Married   
2                          42         KATSINA              Yes        Married   
3                          42           NIGER              Yes         Single   
4                          77       AKWA IBOM              Yes        Married   
...                       ...             ...              ...            ...   
38307                      70           LAGOS              Yes        Married   
38308                      48             IMO              Yes        Married   
38309                      71         ANAMBRA               No        Married   
38310                      37           KWARA              Yes        Married   
38311                      41

In [ ]:
# To check columns in the above data
import numpy as np
import pandas as pd
Promotion_Dataset = pd.read_csv("sample_data/Promotion_Dataset.csv")
Promotion_Dataset.columns

Index(['EmployeeNo', 'Division', 'Qualification', 'Gender',
       'Channel_of_Recruitment', 'Trainings_Attended', 'Year_of_birth',
       'Last_performance_score', 'Year_of_recruitment', 'Targets_met',
       'Previous_Award', 'Training_score_average', 'State_Of_Origin',
       'Foreign_schooled', 'Marital_Status', 'Past_Disciplinary_Action',
       'Previous_IntraDepartmental_Movement', 'No_of_previous_employers',
       'Promoted_or_Not'],
      dtype='object')

In [ ]:
# Checking the head and the tail
Promotion_Dataset.head()

EmployeeNo                               Division        Qualification  \
0  YAK/S/00001         Commercial Sales and Marketing     MSc  MBA and PhD   
1  YAK/S/00002  Customer Support and Field Operations  First Degree or HND   
2  YAK/S/00003         Commercial Sales and Marketing  First Degree or HND   
3  YAK/S/00004         Commercial Sales and Marketing  First Degree or HND   
4  YAK/S/00006               Information and Strategy  First Degree or HND   

   Gender   Channel_of_Recruitment  Trainings_Attended  Year_of_birth  \
0  Female  Direct Internal process                   2           1986   
1    Male        Agency and others                   2           1991   
2    Male  Direct Internal process                   2           1987   
3    Male        Agency and others                   3           1982   
4    Male  Direct Internal process                   3           1990   

   Last_performance_score  Year_of_recruitment  Targets_met  Previous_Award  \
0                    12.5                 2011            1               0   
1                    12.5                 2015            0               0   
2                     7.5                 2012            0               0   
3                     2.5                 2009            0               0   
4                     7.5                 2012            0               0   

   Training_score_average State_Of_Origin Foreign_schooled Marital_Status  \
0                      41         ANAMBRA               No        Married   
1                      52         ANAMBRA              Yes        Married   
2                      42         KATSINA              Yes        Married   
3                      42           NIGER              Yes         Single   
4                      77       AKWA IBOM              Yes        Married   

  Past_Disciplinary_Action Previous_IntraDepartmental_Movement  \
0                       No                                  No   
1                       No                                  No   
2                       No                                  No   
3                       No                                  No   
4                       No                                  No   

   No_of_previous_employers  Promoted_or_Not  
0                         0                0  
1                         0                0  
2                         0                0  
3                         1                0  
4                         1                0

In [ ]:
# tail
Promotion_Dataset.tail()

EmployeeNo                                     Division  \
38307  YAK/S/54802  Information Technology and Solution Support   
38308  YAK/S/54805        Customer Support and Field Operations   
38309  YAK/S/54806                     Information and Strategy   
38310  YAK/S/54807               Commercial Sales and Marketing   
38311  YAK/S/54808                         People/HR Management   

             Qualification  Gender   Channel_of_Recruitment  \
38307  First Degree or HND  Female  Direct Internal process   
38308     MSc  MBA and PhD  Female        Agency and others   
38309  First Degree or HND    Male        Agency and others   
38310                  NaN    Male  Direct Internal process   
38311  First Degree or HND    Male        Agency and others   

       Trainings_Attended  Year_of_birth  Last_performance_score  \
38307                   2           1990                     0.0   
38308                   2           1984                     5.0   
38309                   2           1994                    12.5   
38310                   2           1992                     2.5   
38311                   2           1994                     2.5   

       Year_of_recruitment  Targets_met  Previous_Award  \
38307                 2018            0               0   
38308                 2013            0               0   
38309                 2016            1               0   
38310                 2017            0               0   
38311                 2014            0               0   

       Training_score_average State_Of_Origin Foreign_schooled Marital_Status  \
38307                      70           LAGOS              Yes        Married   
38308                      48             IMO              Yes        Married   
38309                      71         ANAMBRA               No        Married   
38310                      37           KWARA              Yes        Married   
38311                      41           KWARA              Yes         Single   

      Past_Disciplinary_Action Previous_IntraDepartmental_Movement  \
38307                       No                                  No   
38308                       No                                  No   
38309                       No                                  No   
38310                       No                                  No   
38311                       No                                  No   

       No_of_previous_employers  Promoted_or_Not  
38307                         0                0  
38308                         1                0  
38309                         3                0  
38310                         1                0  
38311                         2                0

In [ ]:
# indexing
Promotion_Dataset.index
Promotion_Dataset.index.values

array([    0,     1,     2, ..., 38309, 38310, 38311])

In [ ]:
# Gender
Promotion_Dataset.Gender

0        Female
1          Male
2          Male
3          Male
4          Male
          ...  
38307    Female
38308    Female
38309      Male
38310      Male
38311      Male
Name: Gender, Length: 38312, dtype: object

In [ ]:
# Checking Female Gender
Promotion_Dataset[Promotion_Dataset.Gender == "Female"]

EmployeeNo                                     Division  \
0      YAK/S/00001               Commercial Sales and Marketing   
5      YAK/S/00007        Customer Support and Field Operations   
9      YAK/S/00012               Commercial Sales and Marketing   
16     YAK/S/00023                  Business Finance Operations   
22     YAK/S/00033               Commercial Sales and Marketing   
...            ...                                          ...   
38299  YAK/S/54789               Commercial Sales and Marketing   
38301  YAK/S/54791                         People/HR Management   
38305  YAK/S/54799               Commercial Sales and Marketing   
38307  YAK/S/54802  Information Technology and Solution Support   
38308  YAK/S/54805        Customer Support and Field Operations   

             Qualification  Gender   Channel_of_Recruitment  \
0         MSc  MBA and PhD  Female  Direct Internal process   
5      First Degree or HND  Female        Agency and others   
9      First Degree or HND  Female  Direct Internal process   
16     First Degree or HND  Female        Agency and others   
22                     NaN  Female  Direct Internal process   
...                    ...     ...                      ...   
38299  First Degree or HND  Female  Direct Internal process   
38301  First Degree or HND  Female  Direct Internal process   
38305     MSc  MBA and PhD  Female        Agency and others   
38307  First Degree or HND  Female  Direct Internal process   
38308     MSc  MBA and PhD  Female        Agency and others   

       Trainings_Attended  Year_of_birth  Last_performance_score  \
0                       2           1986                    12.5   
5                       2           1990                     7.5   
9                       2           1986                    12.5   
16                      2           1993                     7.5   
22                      2           1997                     2.5   
...                   ...            ...                     ...   
38299                   3           1993                     7.5   
38301                   2           1973                    12.5   
38305                   3           1981                    12.5   
38307                   2           1990                     0.0   
38308                   2           1984                     5.0   

       Year_of_recruitment  Targets_met  Previous_Award  \
0                     2011            1               0   
5                     2014            0               0   
9                     2016            1               0   
16                    2015            0               0   
22                    2017            0               0   
...                    ...          ...             ...   
38299                 2016            0               0   
38301                 2015            0               0   
38305                 2015            1               0   
38307                 2018            0               0   
38308                 2013            0               0   

       Training_score_average State_Of_Origin Foreign_schooled Marital_Status  \
0                          41         ANAMBRA               No        Married   
5                          51           ENUGU              Yes        Married   
9                          42           LAGOS              Yes        Married   
16                         55          KADUNA              Yes        Married   
22                         40             EDO              Yes        Married   
...                       ...             ...              ...            ...   
38299                      40             FCT              Yes        Married   
38301                      41           DELTA              Yes         Single   
38305                      43             FCT              Yes        Married   
38307                      70           LAGOS              Yes        Married   
38308                      48

In [ ]:
# Checking Qualification = Msc and PhD
Promotion_Dataset[(Promotion_Dataset.Qualification == "Msc") | (Promotion_Dataset.Qualification == "PhD")]

Empty DataFrame
Columns: [EmployeeNo, Division, Qualification, Gender, Channel_of_Recruitment, Trainings_Attended, Year_of_birth, Last_performance_score, Year_of_recruitment, Targets_met, Previous_Award, Training_score_average, State_Of_Origin, Foreign_schooled, Marital_Status, Past_Disciplinary_Action, Previous_IntraDepartmental_Movement, No_of_previous_employers, Promoted_or_Not]
Index: []

In [ ]:
# Checking Qualification index with values
Promotion_Dataset[(Promotion_Dataset.Qualification == "Msc") | (Promotion_Dataset.Qualification == "PhD")].index.values

array([], dtype=int64)

In [ ]:
# Slicing
Promotion_Dataset[0:5]

EmployeeNo                               Division        Qualification  \
0  YAK/S/00001         Commercial Sales and Marketing     MSc  MBA and PhD   
1  YAK/S/00002  Customer Support and Field Operations  First Degree or HND   
2  YAK/S/00003         Commercial Sales and Marketing  First Degree or HND   
3  YAK/S/00004         Commercial Sales and Marketing  First Degree or HND   
4  YAK/S/00006               Information and Strategy  First Degree or HND   

   Gender   Channel_of_Recruitment  Trainings_Attended  Year_of_birth  \
0  Female  Direct Internal process                   2           1986   
1    Male        Agency and others                   2           1991   
2    Male  Direct Internal process                   2           1987   
3    Male        Agency and others                   3           1982   
4    Male  Direct Internal process                   3           1990   

   Last_performance_score  Year_of_recruitment  Targets_met  Previous_Award  \
0                    12.5                 2011            1               0   
1                    12.5                 2015            0               0   
2                     7.5                 2012            0               0   
3                     2.5                 2009            0               0   
4                     7.5                 2012            0               0   

   Training_score_average State_Of_Origin Foreign_schooled Marital_Status  \
0                      41         ANAMBRA               No        Married   
1                      52         ANAMBRA              Yes        Married   
2                      42         KATSINA              Yes        Married   
3                      42           NIGER              Yes         Single   
4                      77       AKWA IBOM              Yes        Married   

  Past_Disciplinary_Action Previous_IntraDepartmental_Movement  \
0                       No                                  No   
1                       No                                  No   
2                       No                                  No   
3                       No                                  No   
4                       No                                  No   

   No_of_previous_employers  Promoted_or_Not  
0                         0                0  
1                         0                0  
2                         0                0  
3                         1                0  
4                         1                0

In [ ]:
!ls /content/

'Churn_Modelling Dataset.csv'   drive   sample_data


# Importing data from Excel

 With .xlsx or xls format all you need is pd.read_excel() command to load in the data.

 # Example 2

 Load the East_Africa-names.xlsx which was scrapped from https://www.behindthename.com/submit/names/usage/eastern-african. Since you have imported all the necessary libraries such as numpy and pandas .You don't need to import them here again.

In [ ]:
# Example : loading east_africa_names.xlsx
import numpy as np
import pandas as pd
east_africa_names = pd.read_excel("datasets/East_Africa-names.xlsx")
east_africa_names


FileNotFoundError: [Errno 2] No such file or directory: 'datasets/East_Africa-names.xlsx'

* Excel workbook can have many worksheets and can  host different data .while importing your data,you need to specify the index of the sheet that you want to import.

* Remember Python index start from 0.

In [ ]:
# Example: sheet_names = 0, =>it will print 1st sheet from excel page
east_africa_names = pd.read.excel("datasets/east-Africa-names.xlxs",  sheet_name= 0)
east_africa_names

**Note**

* while importing excel data using above code, you alterantively write specify the *sheet_name = sheet1* instead of *sheet_name = 0*

 * it will be observed that *sheet_name = 0*, means that *sheet 1* from the excel page will be dispalyed,meanwhile if the *sheet_name = 1*,the second sheet is displayed.

Therefore, it is necessary to specify the sheet name or number to avoid error.

 To check the columns in the east_africa_names data the code is written thus:

In [ ]:
import numpy as np
import pandas as pd
east_africa_names.columns


You have imported East Africa names successfully! You

are now an expert in importing file!

Let's see various names in the east_africa_names data we just imported.

In [ ]:
# Checking head
east_africa_names.head()

In [ ]:
# Checking tail
east_africa_names.tail()

As you can see a given name can come from more than 1 origin and also both sex can bear that name .The * NaN* in some of the columns means that the values are not available.

# Import data from JSON
.JSON stands for JavaScript object Notation. With *.json* format all you need is pd.read_json() command to load in the data.

# Example

Load *anscombe.json* data and determing the head and the tail.


In [ ]:
# Loading anscombe data
anscombe_data = pd.read_json("sample_data/anscombe.json")
anscombe_data

Series   X      Y
0       I  10   8.04
1       I   8   6.95
2       I  13   7.58
3       I   9   8.81
4       I  11   8.33
5       I  14   9.96
6       I   6   7.24
7       I   4   4.26
8       I  12  10.84
9       I   7   4.81
10      I   5   5.68
11     II  10   9.14
12     II   8   8.14
13     II  13   8.74
14     II   9   8.77
15     II  11   9.26
16     II  14   8.10
17     II   6   6.13
18     II   4   3.10
19     II  12   9.13
20     II   7   7.26
21     II   5   4.74
22    III  10   7.46
23    III   8   6.77
24    III  13  12.74
25    III   9   7.11
26    III  11   7.81
27    III  14   8.84
28    III   6   6.08
29    III   4   5.39
30    III  12   8.15
31    III   7   6.42
32    III   5   5.73
33     IV   8   6.58
34     IV   8   5.76
35     IV   8   7.71
36     IV   8   8.84
37     IV   8   8.47
38     IV   8   7.04
39     IV   8   5.25
40     IV  19  12.50
41     IV   8   5.56
42     IV   8   7.91
43     IV   8   6.89

In [ ]:
# Data Information
anscombe_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Series  44 non-null     object 
 1   X       44 non-null     int64  
 2   Y       44 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.2+ KB


In [ ]:
# Determining the tail
anscombe_data.tail()

Series   X      Y
39     IV   8   5.25
40     IV  19  12.50
41     IV   8   5.56
42     IV   8   7.91
43     IV   8   6.89

In [ ]:
# Determining the head
anscombe_data.head()

Series   X     Y
0      I  10  8.04
1      I   8  6.95
2      I  13  7.58
3      I   9  8.81
4      I  11  8.33

# Export Data With Pandas

You can save DataFrame in Python to any file of your choice.Similar to the ways we read in data pandas provides intuitive commandas to save it.

1. *df.to_csv('new-file.csv')* # to save as csv file

2. *df.to_excel('new_file.xlsx')* # to save as Excel file.

3. *df.to_json('new_file.json')* # to save as JSON file

When we save as csv, xlsx, or any file formats.all we have to input into thse functions is our desired filename with the appropriate file extension.





# Example

Import fatal-police-shootings-data.csv data as police_shooting and export the resulting DataFrame as:

1. .dta

2. .xlsx

3. .json

# Solution


In [ ]:
import pandas as pd
mnist_test = pd.read_csv("/content/sample_data/mnist_test.csv")
mnist_test

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [ ]:
# Data information
mnist_test.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Columns: 785 entries, 7 to 0.667
dtypes: int64(785)
memory usage: 59.9 MB


# To export as dta(STATA file), we use:

In [ ]:
# To export as dta (STATA file)
mnist_test.to_stata("mnist_test.dta")

/tmp/ipython-input-3032387607.py:2: InvalidColumnName: 
Not all pandas column names were valid Stata variable names.
The following replacements have been made:

    7   ->   _7
    0   ->   _0
    0.1   ->   _0_1
    0.2   ->   _0_2
    0.3   ->   _0_3
    0.4   ->   _0_4
    0.5   ->   _0_5
    0.6   ->   _0_6
    0.7   ->   _0_7
    0.8   ->   _0_8
    0.9   ->   _0_9
    0.10   ->   _0_10
    0.11   ->   _0_11
    0.12   ->   _0_12
    0.13   ->   _0_13
    0.14   ->   _0_14
    0.15   ->   _0_15
    0.16   ->   _0_16
    0.17   ->   _0_17
    0.18   ->   _0_18
    0.19   ->   _0_19
    0.20   ->   _0_20
    0.21   ->   _0_21
    0.22   ->   _0_22
    0.23   ->   _0_23
    0.24   ->   _0_24
    0.25   ->   _0_25
    0.26   ->   _0_26
    0.27   ->   _0_27
    0.28   ->   _0_28
    0.29   ->   _0_29
    0.30   ->   _0_30
    0.31   ->   _0_31
    0.32   ->   _0_32
    0.33   ->   _0_33
    0.34   ->   _0_34
    0.35   ->   _0_35
    0.36   ->   _0_36
    0.37   ->   _0_37
    0.38   

In [ ]:
# renaming
mnsit_test.rename

NameError: name 'mnsit_test' is not defined

# To export as dta (STATA file),we use:

In [ ]:
import pandas as pd
mnist_test = pd.read_csv("/content/sample_data/mnist_test.csv")
mnist_test.to_stata("/content/sample_data/mnist_test.dta")

/tmp/ipython-input-2587978897.py:3: InvalidColumnName: 
Not all pandas column names were valid Stata variable names.
The following replacements have been made:

    7   ->   _7
    0   ->   _0
    0.1   ->   _0_1
    0.2   ->   _0_2
    0.3   ->   _0_3
    0.4   ->   _0_4
    0.5   ->   _0_5
    0.6   ->   _0_6
    0.7   ->   _0_7
    0.8   ->   _0_8
    0.9   ->   _0_9
    0.10   ->   _0_10
    0.11   ->   _0_11
    0.12   ->   _0_12
    0.13   ->   _0_13
    0.14   ->   _0_14
    0.15   ->   _0_15
    0.16   ->   _0_16
    0.17   ->   _0_17
    0.18   ->   _0_18
    0.19   ->   _0_19
    0.20   ->   _0_20
    0.21   ->   _0_21
    0.22   ->   _0_22
    0.23   ->   _0_23
    0.24   ->   _0_24
    0.25   ->   _0_25
    0.26   ->   _0_26
    0.27   ->   _0_27
    0.28   ->   _0_28
    0.29   ->   _0_29
    0.30   ->   _0_30
    0.31   ->   _0_31
    0.32   ->   _0_32
    0.33   ->   _0_33
    0.34   ->   _0_34
    0.35   ->   _0_35
    0.36   ->   _0_36
    0.37   ->   _0_37
    0.38   

In [ ]:
# head
import pandas as pd
mnsit_test = pd.read_csv("/content/sample_data/mnist_test.csv")
mnsit_test.head()

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [ ]:
# tail
import pandas as pd
mnsit_test = pd.read_csv("/content/sample_data/mnist_test.csv")
mnsit_test.tail()

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[5 rows x 785 columns]

from matplotlib import pyplot as plt
_df_0['7'].plot(kind='hist', bins=20, title='7')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['0.73'].plot(kind='hist', bins=20, title='0.73')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['0.74'].plot(kind='hist', bins=20, title='0.74')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['0.75'].plot(kind='hist', bins=20, title='0.75')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='7', y='0.73', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='0.73', y='0.74', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='0.74', y='0.75', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='0.75', y='0.76', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['7']
  ys = series['0.122']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('7', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('7')
_ = plt.ylabel('0.122')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['7']
  ys = series['0.123']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('7', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('7')
_ = plt.ylabel('0.123')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['7']
  ys = series['0.124']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('7', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('7')
_ = plt.ylabel('0.124')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['7']
  ys = series['0.125']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('7', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('7')
_ = plt.ylabel('0.125')

from matplotlib import pyplot as plt
_df_12['7'].plot(kind='line', figsize=(8, 4), title='7')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_13['0.73'].plot(kind='line', figsize=(8, 4), title='0.73')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['0.74'].plot(kind='line', figsize=(8, 4), title='0.74')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['0.75'].plot(kind='line', figsize=(8, 4), title='0.75')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
import pandas as pd

# Reload the dataset as the previous steps might have modified it in memory
mnist_test = pd.read_csv("/content/sample_data/mnist_test.csv")

# Create a dictionary to map old column names to new Stata-compatible names
new_columns = {col: 'col_' + str(col).replace('.', '_') for col in mnist_test.columns}

# Rename the columns
mnist_test = mnist_test.rename(columns=new_columns)

print("New column names:")
print(mnist_test.columns.tolist())


New column names:
['col_7', 'col_0', 'col_0_1', 'col_0_2', 'col_0_3', 'col_0_4', 'col_0_5', 'col_0_6', 'col_0_7', 'col_0_8', 'col_0_9', 'col_0_10', 'col_0_11', 'col_0_12', 'col_0_13', 'col_0_14', 'col_0_15', 'col_0_16', 'col_0_17', 'col_0_18', 'col_0_19', 'col_0_20', 'col_0_21', 'col_0_22', 'col_0_23', 'col_0_24', 'col_0_25', 'col_0_26', 'col_0_27', 'col_0_28', 'col_0_29', 'col_0_30', 'col_0_31', 'col_0_32', 'col_0_33', 'col_0_34', 'col_0_35', 'col_0_36', 'col_0_37', 'col_0_38', 'col_0_39', 'col_0_40', 'col_0_41', 'col_0_42', 'col_0_43', 'col_0_44', 'col_0_45', 'col_0_46', 'col_0_47', 'col_0_48', 'col_0_49', 'col_0_50', 'col_0_51', 'col_0_52', 'col_0_53', 'col_0_54', 'col_0_55', 'col_0_56', 'col_0_57', 'col_0_58', 'col_0_59', 'col_0_60', 'col_0_61', 'col_0_62', 'col_0_63', 'col_0_64', 'col_0_65', 'col_0_66', 'col_0_67', 'col_0_68', 'col_0_69', 'col_0_70', 'col_0_71', 'col_0_72', 'col_0_73', 'col_0_74', 'col_0_75', 'col_0_76', 'col_0_77', 'col_0_78', 'col_0_79', 'col_0_80', 'col_0_81', 

In [ ]:
# Now, export the DataFrame to a Stata file with the compatible column names
mnist_test.to_stata("/content/sample_data/mnist_test_renamed.dta")
print("DataFrame successfully exported to /content/sample_data/mnist_test_renamed.dta")


DataFrame successfully exported to /content/sample_data/mnist_test_renamed.dta


In [ ]:
mnist_test.columns

Index(['7', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8',
       ...
       '0.658', '0.659', '0.660', '0.661', '0.662', '0.663', '0.664', '0.665',
       '0.666', '0.667'],
      dtype='object', length=785)

In [ ]:
# Slicing
import pandas as pd
mnsit_test = pd.read_csv("/content/sample_data/mnist_test.csv")
mnsit_test[0:5]

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [ ]:
# indexing
import pandas as pd
mnsit_test = pd.read_csv("/content/sample_data/mnist_test.csv")
mnsit_test.index
mnsit_test.index.values


array([   0,    1,    2, ..., 9996, 9997, 9998])

# To export as *.xlsx* (Excel file), we use:


In [ ]:
# Exporting csv as .xlsx (Excel file), we use:
import pandas as pd
mnist_test = pd.read_csv("/content/sample_data/mnist_test.csv")
mnist_test.to_excel("/content/sample_data/mnist_test.xlsx")


In [ ]:
mnsit_test.to_excel("/content/sample_data/mnsit_test.xlsx")

# To export csv as *.json* (JSON file), we use:

In [ ]:
# Exporting csv as .json (JSON file) we use:
import pandas as pd
mnist_test = pd.read_csv("/content/sample_data/mnist_test.csv")
mnist_test.to_json("/content/sample_data/mnist_test.json")

In [ ]:
# Exercises


# Data Cleaning

* How to recognise missing values with pandas.

* How to do statistics of missing values with pandas.

# Working with missing data

In this section we will discuss values also referred to as **NA**, **NaN** or **NULL** in pandas.

When exploring data you'll most likely encounter missing values, which symbolically represent non-existence values.

We can check whether there are missing values in one or more columns of a DataFrame by using *.isna()*or *.isnull()* while *.isna().sum()* or *.isnull().sum() can be used to get the number of missing values in each of the columns of DataFrame.

We check whether there is missing value by using followings:

* *.isna()*

 or

* *.isnull()*



# Example 1

Import Promotion_Dataset.csv dataset and count the number of missing values in its columns.


In [ ]:
# import Promotion_Dataset.csv
import pandas as pd
Promotion_Dataset = pd.read_csv("/content/drive/MyDrive/DSA_ML/Promotion_Dataset.csv")

In [ ]:
Promotion_Dataset

EmployeeNo                                     Division  \
0      YAK/S/00001               Commercial Sales and Marketing   
1      YAK/S/00002        Customer Support and Field Operations   
2      YAK/S/00003               Commercial Sales and Marketing   
3      YAK/S/00004               Commercial Sales and Marketing   
4      YAK/S/00006                     Information and Strategy   
...            ...                                          ...   
38307  YAK/S/54802  Information Technology and Solution Support   
38308  YAK/S/54805        Customer Support and Field Operations   
38309  YAK/S/54806                     Information and Strategy   
38310  YAK/S/54807               Commercial Sales and Marketing   
38311  YAK/S/54808                         People/HR Management   

             Qualification  Gender   Channel_of_Recruitment  \
0         MSc  MBA and PhD  Female  Direct Internal process   
1      First Degree or HND    Male        Agency and others   
2      First Degree or HND    Male  Direct Internal process   
3      First Degree or HND    Male        Agency and others   
4      First Degree or HND    Male  Direct Internal process   
...                    ...     ...                      ...   
38307  First Degree or HND  Female  Direct Internal process   
38308     MSc  MBA and PhD  Female        Agency and others   
38309  First Degree or HND    Male        Agency and others   
38310                  NaN    Male  Direct Internal process   
38311  First Degree or HND    Male        Agency and others   

       Trainings_Attended  Year_of_birth  Last_performance_score  \
0                       2           1986                    12.5   
1                       2           1991                    12.5   
2                       2           1987                     7.5   
3                       3           1982                     2.5   
4                       3           1990                     7.5   
...                   ...            ...                     ...   
38307                   2           1990                     0.0   
38308                   2           1984                     5.0   
38309                   2           1994                    12.5   
38310                   2           1992                     2.5   
38311                   2           1994                     2.5   

       Year_of_recruitment  Targets_met  Previous_Award  \
0                     2011            1               0   
1                     2015            0               0   
2                     2012            0               0   
3                     2009            0               0   
4                     2012            0               0   
...                    ...          ...             ...   
38307                 2018            0               0   
38308                 2013            0               0   
38309                 2016            1               0   
38310                 2017            0               0   
38311                 2014            0               0   

       Training_score_average State_Of_Origin Foreign_schooled Marital_Status  \
0                          41         ANAMBRA               No        Married   
1                          52         ANAMBRA              Yes        Married   
2                          42         KATSINA              Yes        Married   
3                          42           NIGER              Yes         Single   
4                          77       AKWA IBOM              Yes        Married   
...                       ...             ...              ...            ...   
38307                      70           LAGOS              Yes        Married   
38308                      48             IMO              Yes        Married   
38309                      71         ANAMBRA               No        Married   
38310                      37           KWARA              Yes        Married   
38311                      41

In [ ]:
import numpy as pd
import pandas as pd
Promotion_Dataset = pd.read_csv("/content/drive/MyDrive/DSA_ML/Promotion_Dataset.csv")
Promotion_Dataset.isna()

EmployeeNo  Division  Qualification  Gender  Channel_of_Recruitment  \
0           False     False          False   False                   False   
1           False     False          False   False                   False   
2           False     False          False   False                   False   
3           False     False          False   False                   False   
4           False     False          False   False                   False   
...           ...       ...            ...     ...                     ...   
38307       False     False          False   False                   False   
38308       False     False          False   False                   False   
38309       False     False          False   False                   False   
38310       False     False           True   False                   False   
38311       False     False          False   False                   False   

       Trainings_Attended  Year_of_birth  Last_performance_score  \
0                   False          False                   False   
1                   False          False                   False   
2                   False          False                   False   
3                   False          False                   False   
4                   False          False                   False   
...                   ...            ...                     ...   
38307               False          False                   False   
38308               False          False                   False   
38309               False          False                   False   
38310               False          False                   False   
38311               False          False                   False   

       Year_of_recruitment  Targets_met  Previous_Award  \
0                    False        False           False   
1                    False        False           False   
2                    False        False           False   
3                    False        False           False   
4                    False        False           False   
...                    ...          ...             ...   
38307                False        False           False   
38308                False        False           False   
38309                False        False           False   
38310                False        False           False   
38311                False        False           False   

       Training_score_average  State_Of_Origin  Foreign_schooled  \
0                       False            False             False   
1                       False            False             False   
2                       False            False             False   
3                       False            False             False   
4                       False            False             False   
...                       ...              ...               ...   
38307                   False            False             False   
38308                   False            False             False   
38309                   False            False             False   
38310                   False            False             False   
38311                   False            False             False   

       Marital_Status  Past_Disciplinary_Action  \
0               False                     False   
1               False                     False   
2               False                     False   
3               False                     False   
4               False                     False   
...               ...                       ...   
38307           False                     False   
38308           False                     False   
38309           False                     False   
38310           False                     False   
38311           False                     False   

       Previous_IntraDepartmental_Movement  No_of_previous_employers  \
0                                    False

As you can see, there are some values missing in the qualification column of the Promotion_Dataset Dataframe.To get the number of missing values we use *.isna().sum().

In [ ]:
# Getting missing values by using .isna().sum():
import numpy as pd
import pandas as pd
Promotion_Dataset = pd.read_csv("/content/drive/MyDrive/DSA_ML/Promotion_Dataset.csv")
Promotion_Dataset.isna().sum()

EmployeeNo                                0
Division                                  0
Qualification                          1679
Gender                                    0
Channel_of_Recruitment                    0
Trainings_Attended                        0
Year_of_birth                             0
Last_performance_score                    0
Year_of_recruitment                       0
Targets_met                               0
Previous_Award                            0
Training_score_average                    0
State_Of_Origin                           0
Foreign_schooled                          0
Marital_Status                            0
Past_Disciplinary_Action                  0
Previous_IntraDepartmental_Movement       0
No_of_previous_employers                  0
Promoted_or_Not                           0
dtype: int64

We can also get missing values by using the following codes:

*.isnull().sum()*

In [ ]:
# Exammple:Getting missing values using .isnull.sum()
import numpy as pd
import pandas as pd
Promotion_Dataset = pd.read_csv("/content/drive/MyDrive/DSA_ML/Promotion_Dataset.csv")
Promotion_Dataset.isnull().sum()


EmployeeNo                                0
Division                                  0
Qualification                          1679
Gender                                    0
Channel_of_Recruitment                    0
Trainings_Attended                        0
Year_of_birth                             0
Last_performance_score                    0
Year_of_recruitment                       0
Targets_met                               0
Previous_Award                            0
Training_score_average                    0
State_Of_Origin                           0
Foreign_schooled                          0
Marital_Status                            0
Past_Disciplinary_Action                  0
Previous_IntraDepartmental_Movement       0
No_of_previous_employers                  0
Promoted_or_Not                           0
dtype: int64

**Note**

As you can see there are missing values in qualification column amounting to about *1679* .

# Data Imputation

 **Strategies**

There are two options in dealing with missing values:

1. Get rid of rows or columns with nulls

2. Replace nulls with non-null values which is known as data imputation.

3. Machine Learning



# Strategy 1

# 1. Getting rid of rows or columns with nulls

 * Every data scientist or analyst regularly face the problem of whether to remove (drop) the missing values(NA, NULL, or NAN) or imputate them.

 * This is a decision that requires intimate knowlegde of your data and its content.Overall, removing null data is only suggested if you have a small amount of missing data.

 * Removing nulls is pretty simple by using *.dropna()*.


# Example 1

For example let's remove the missing values in the Promotion dataset.Remember in our Promotion_Dataset DataFrame, there are some missing values in qualification column.


In [ ]:
# Step 1: Check the head of promotion dataset
Promotion_Dataset.head()

EmployeeNo                               Division        Qualification  \
0  YAK/S/00001         Commercial Sales and Marketing     MSc  MBA and PhD   
1  YAK/S/00002  Customer Support and Field Operations  First Degree or HND   
2  YAK/S/00003         Commercial Sales and Marketing  First Degree or HND   
3  YAK/S/00004         Commercial Sales and Marketing  First Degree or HND   
4  YAK/S/00006               Information and Strategy  First Degree or HND   

   Gender   Channel_of_Recruitment  Trainings_Attended  Year_of_birth  \
0  Female  Direct Internal process                   2           1986   
1    Male        Agency and others                   2           1991   
2    Male  Direct Internal process                   2           1987   
3    Male        Agency and others                   3           1982   
4    Male  Direct Internal process                   3           1990   

   Last_performance_score  Year_of_recruitment  Targets_met  Previous_Award  \
0                    12.5                 2011            1               0   
1                    12.5                 2015            0               0   
2                     7.5                 2012            0               0   
3                     2.5                 2009            0               0   
4                     7.5                 2012            0               0   

   Training_score_average State_Of_Origin Foreign_schooled Marital_Status  \
0                      41         ANAMBRA               No        Married   
1                      52         ANAMBRA              Yes        Married   
2                      42         KATSINA              Yes        Married   
3                      42           NIGER              Yes         Single   
4                      77       AKWA IBOM              Yes        Married   

  Past_Disciplinary_Action Previous_IntraDepartmental_Movement  \
0                       No                                  No   
1                       No                                  No   
2                       No                                  No   
3                       No                                  No   
4                       No                                  No   

   No_of_previous_employers  Promoted_or_Not  
0                         0                0  
1                         0                0  
2                         0                0  
3                         1                0  
4                         1                0

Let's use *.shape* to check the number of rows and columns before removing any missing values.

In [ ]:
# Step 2: Check the shape of Promotion_Dataset;
Promotion_Dataset.shape


(38312, 19)

 Now let's drop those missing values *.dropna() attribute.This action will delete any row with at least a single NA, Null, or NAN value.

 But it will return a new DataFrame without altering the original one.You could specify *inplace=True* in this method as well.

In [ ]:
# Step 3: Using drop attribute for Promotion_Dataset
Promotion_Dataset.dropna()

EmployeeNo                                     Division  \
0      YAK/S/00001               Commercial Sales and Marketing   
1      YAK/S/00002        Customer Support and Field Operations   
2      YAK/S/00003               Commercial Sales and Marketing   
3      YAK/S/00004               Commercial Sales and Marketing   
4      YAK/S/00006                     Information and Strategy   
...            ...                                          ...   
38306  YAK/S/54801                         People/HR Management   
38307  YAK/S/54802  Information Technology and Solution Support   
38308  YAK/S/54805        Customer Support and Field Operations   
38309  YAK/S/54806                     Information and Strategy   
38311  YAK/S/54808                         People/HR Management   

             Qualification  Gender   Channel_of_Recruitment  \
0         MSc  MBA and PhD  Female  Direct Internal process   
1      First Degree or HND    Male        Agency and others   
2      First Degree or HND    Male  Direct Internal process   
3      First Degree or HND    Male        Agency and others   
4      First Degree or HND    Male  Direct Internal process   
...                    ...     ...                      ...   
38306  First Degree or HND    Male        Agency and others   
38307  First Degree or HND  Female  Direct Internal process   
38308     MSc  MBA and PhD  Female        Agency and others   
38309  First Degree or HND    Male        Agency and others   
38311  First Degree or HND    Male        Agency and others   

       Trainings_Attended  Year_of_birth  Last_performance_score  \
0                       2           1986                    12.5   
1                       2           1991                    12.5   
2                       2           1987                     7.5   
3                       3           1982                     2.5   
4                       3           1990                     7.5   
...                   ...            ...                     ...   
38306                   3           1987                    12.5   
38307                   2           1990                     0.0   
38308                   2           1984                     5.0   
38309                   2           1994                    12.5   
38311                   2           1994                     2.5   

       Year_of_recruitment  Targets_met  Previous_Award  \
0                     2011            1               0   
1                     2015            0               0   
2                     2012            0               0   
3                     2009            0               0   
4                     2012            0               0   
...                    ...          ...             ...   
38306                 2016            0               0   
38307                 2018            0               0   
38308                 2013            0               0   
38309                 2016            1               0   
38311                 2014            0               0   

       Training_score_average State_Of_Origin Foreign_schooled Marital_Status  \
0                          41         ANAMBRA               No        Married   
1                          52         ANAMBRA              Yes        Married   
2                          42         KATSINA              Yes        Married   
3                          42           NIGER              Yes         Single   
4                          77       AKWA IBOM              Yes        Married   
...                       ...             ...              ...            ...   
38306                      44           LAGOS              Yes        Married   
38307                      70           LAGOS              Yes        Married   
38308                      48             IMO              Yes        Married   
38309                      71         ANAMBRA               No        Married   
38311                      41

**Note**

* You will notice that prior to using *drop attiribute*, the shape of the promotion dataset was *38312 rows and 19 columns*.

* After using the *drop attibute* the data shape change to *36633 rows and 19 columns*.In which  *1679 rows* were dropped due to missing values.

* Also, other than just dropping rows, you can drop columns with null values by seting axis = "columns" or 1

**Important Note**

Sometimes there can be *UnicodeDecodeError* when reading CSV file in Pandas with Python .You will notice that I  used *encoding = "150-8859-1"* option to stop this error.

# Example 2

Import Churn_Modelling dataset.csv, identify missing data and clean  it using *isna()*, *.isnull()*.






In [ ]:
# Importing Churn_Modelling_Dataset
import numpy as np
import pandas as pd
churn_modelling_dataset = pd.read_csv("/content/drive/MyDrive/DSA_ML/Churn_Modelling Dataset.csv")
churn_modelling_dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Churn  
0           101348.88      1  
1           112542.58      0  
2           113931.57      1  
3            93826.63      0  
4            79084.10      0  
...               ...    ...  
9995         96270.64      0  
9996        101699.77      0  
9997         42085.58      1  
9998         92888.52      1  
9999         38190.78      0  

[10000 rows x 14 columns]

In [ ]:
churn_modelling_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Churn            10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [ ]:
# Determine the head:
churn_modelling_dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Churn  
0        101348.88      1  
1        112542.58      0  
2        113931.57      1  
3         93826.63      0  
4         79084.10      0

In [ ]:
# calculating tail:
churn_modelling_dataset.tail()

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Churn  
9995         96270.64      0  
9996        101699.77      0  
9997         42085.58      1  
9998         92888.52      1  
9999         38190.78      0

In [ ]:
# checking missing values:
churn_modelling_dataset.isna()

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender    Age  \
0         False       False    False        False      False   False  False   
1         False       False    False        False      False   False  False   
2         False       False    False        False      False   False  False   
3         False       False    False        False      False   False  False   
4         False       False    False        False      False   False  False   
...         ...         ...      ...          ...        ...     ...    ...   
9995      False       False    False        False      False   False  False   
9996      False       False    False        False      False   False  False   
9997      False       False    False        False      False   False  False   
9998      False       False    False        False      False   False  False   
9999      False       False    False        False      False   False  False   

      Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0      False    False          False      False           False   
1      False    False          False      False           False   
2      False    False          False      False           False   
3      False    False          False      False           False   
4      False    False          False      False           False   
...      ...      ...            ...        ...             ...   
9995   False    False          False      False           False   
9996   False    False          False      False           False   
9997   False    False          False      False           False   
9998   False    False          False      False           False   
9999   False    False          False      False           False   

      EstimatedSalary  Churn  
0               False  False  
1               False  False  
2               False  False  
3               False  False  
4               False  False  
...               ...    ...  
9995            False  False  
9996            False  False  
9997            False  False  
9998            False  False  
9999            False  False  

[10000 rows x 14 columns]

In [ ]:
# Checking missing values using .isnull
churn_modelling_dataset.isnull()

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender    Age  \
0         False       False    False        False      False   False  False   
1         False       False    False        False      False   False  False   
2         False       False    False        False      False   False  False   
3         False       False    False        False      False   False  False   
4         False       False    False        False      False   False  False   
...         ...         ...      ...          ...        ...     ...    ...   
9995      False       False    False        False      False   False  False   
9996      False       False    False        False      False   False  False   
9997      False       False    False        False      False   False  False   
9998      False       False    False        False      False   False  False   
9999      False       False    False        False      False   False  False   

      Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0      False    False          False      False           False   
1      False    False          False      False           False   
2      False    False          False      False           False   
3      False    False          False      False           False   
4      False    False          False      False           False   
...      ...      ...            ...        ...             ...   
9995   False    False          False      False           False   
9996   False    False          False      False           False   
9997   False    False          False      False           False   
9998   False    False          False      False           False   
9999   False    False          False      False           False   

      EstimatedSalary  Churn  
0               False  False  
1               False  False  
2               False  False  
3               False  False  
4               False  False  
...               ...    ...  
9995            False  False  
9996            False  False  
9997            False  False  
9998            False  False  
9999            False  False  

[10000 rows x 14 columns]

In [ ]:
# Shape of Data
churn_modelling_dataset.shape

(10000, 14)

**Note**

* Upon checking missing values using *isna() or .isnull()* the ouput shows are there are total of *10000 rows and 14 columns* with no single missing value.

* As such we cannot use drop attribute on *churn_modelling_dataset*

* drop attribute is iven as:
*.dropna() or .dropna(axis = "columns")* .


# Example 2

Import california_housing_test.csv dat, identify missing data and drop them using appropriate code.


In [ ]:
# Importing california_housing_test.csv
import numpy as np
import pandas as pd
california_housing_test = pd.read_csv("/content/sample_data/california_housing_test.csv")
california_housing_test

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0   
1       -118.30     34.26                43.0       1510.0           310.0   
2       -117.81     33.78                27.0       3589.0           507.0   
3       -118.36     33.82                28.0         67.0            15.0   
4       -119.67     36.33                19.0       1241.0           244.0   
...         ...       ...                 ...          ...             ...   
2995    -119.86     34.42                23.0       1450.0           642.0   
2996    -118.14     34.06                27.0       5257.0          1082.0   
2997    -119.70     36.30                10.0        956.0           201.0   
2998    -117.12     34.10                40.0         96.0            14.0   
2999    -119.63     34.42                42.0       1765.0           263.0   

      population  households  median_income  median_house_value  
0         1537.0       606.0         6.6085            344700.0  
1          809.0       277.0         3.5990            176500.0  
2         1484.0       495.0         5.7934            270500.0  
3           49.0        11.0         6.1359            330000.0  
4          850.0       237.0         2.9375             81700.0  
...          ...         ...            ...                 ...  
2995      1258.0       607.0         1.1790            225000.0  
2996      3496.0      1036.0         3.3906            237200.0  
2997       693.0       220.0         2.2895             62000.0  
2998        46.0        14.0         3.2708            162500.0  
2999       753.0       260.0         8.5608            500001.0  

[3000 rows x 9 columns]

Step 1: Check information on california_housing_test.

In [ ]:
# Example 1 : Checking information on california_housing_test.csv
california_housing_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB


Step 2: Checking missing values using *.isna()* and *isnull()*

In [ ]:
# step 2: Checking missing values using *isna()
california_housing_test.isna()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0         False     False               False        False           False   
1         False     False               False        False           False   
2         False     False               False        False           False   
3         False     False               False        False           False   
4         False     False               False        False           False   
...         ...       ...                 ...          ...             ...   
2995      False     False               False        False           False   
2996      False     False               False        False           False   
2997      False     False               False        False           False   
2998      False     False               False        False           False   
2999      False     False               False        False           False   

      population  households  median_income  median_house_value  
0          False       False          False               False  
1          False       False          False               False  
2          False       False          False               False  
3          False       False          False               False  
4          False       False          False               False  
...          ...         ...            ...                 ...  
2995       False       False          False               False  
2996       False       False          False               False  
2997       False       False          False               False  
2998       False       False          False               False  
2999       False       False          False               False  

[3000 rows x 9 columns]

# Step 3

Checking missing values using *.isnull()*

In [5]:
# Step 3: checking missing values using .isnull()
california_housing_test.isnull()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0         False     False               False        False           False   
1         False     False               False        False           False   
2         False     False               False        False           False   
3         False     False               False        False           False   
4         False     False               False        False           False   
...         ...       ...                 ...          ...             ...   
2995      False     False               False        False           False   
2996      False     False               False        False           False   
2997      False     False               False        False           False   
2998      False     False               False        False           False   
2999      False     False               False        False           False   

      population  households  median_income  median_house_value  
0          False       False          False               False  
1          False       False          False               False  
2          False       False          False               False  
3          False       False          False               False  
4          False       False          False               False  
...          ...         ...            ...                 ...  
2995       False       False          False               False  
2996       False       False          False               False  
2997       False       False          False               False  
2998       False       False          False               False  
2999       False       False          False               False  

[3000 rows x 9 columns]

In [7]:
# Checking if the data is boolean in nature.
bool("california_housing_test.isnull()")

True